### ISSUE TITLE
Wrong tag

### ISSUE THREAD

**Issue by Domosed-gamin** [veselov/clines#3]
Please change tag. Not shell. Needed c lang tag. See screen.

https://imgur.com/a/9meHsf9

P.S. Game is awesome!

**Comment by veselov** [comment]
Thank you for your kind words!
The tag of a project is not something that the owner of the repository controls. It seems to be determined by GitHub itself.
There is a related discussion here : https://github.community/t5/How-to-use-Git-and-GitHub/how-to-change-the-category/td-p/27790
It's possible that because of all the auto-configure files, GitHub thinks it's mostly shell code rather than mostly C code.
If you have a merge request that you believe will address that (AFAIU, creating proper .gitattributes files), I'd definitely consider it.
Thank you!

**Comment by Domosed-gamin** [comment]
Ok. I'm nab, not programmer. I not know what is means "merge request", ".gitattributes files" etc. I'm just ASCII gamer. I love CLI/TUI games. Anyway thank you for game. I close this issue.
